marker: 
    debug: False  # [bool] Debug mode.
    in_folder: "./data/etc"  # [str] dir path containing PDFs to convert
    output_dir: "./output"  # [str] Output directory for converted files.
    output_format: "markdown" # [markdown|json|html]
    chunk_idx: 0  # [int] Chunk index to convert, 파일 시작 지정.
    num_chunks: 1  # [int] Number of chunks being processed in parallel. 몇 개의 파일을 변환할 건지 지정.
    max_files: null # [int] Maximum number of PDFs to convert. 최대 몇 개의 파일까지 변환할 건지 지정.
    workers: 5  # [int] Number of worker processes to use.
    skip_existing: False  # [bool] 기존 변환된 파일을 건너뛸 수 있습니다.
    page_range: "0" # [str] Specify which pages to process. Accepts comma-separated page numbers and ranges. Example: "0,5-10,20" will process pages 0, 5 through 10, and page 20.
    # force_ocr: False    # [bool] Force OCR for PDFs.
    # language: "eng"   # [str] Language code for Tesseract OCR. e.g. "ko"